#!/usr/bin/php
<?php
	// load all .class.php files in a directory
	function classes_load( $dir = null, $flag_print = false )
	{
		if( ! $dir )
			throw new Exception('dir not specified');
		
		$dir = dirname(__FILE__).'/'.$dir;
		
		if( ! is_dir($dir) )
			throw new Exception('dir "'.$dir.'" not found');
		
		foreach( glob($dir.'/*.class.php') as $file )
		{
			if( is_dir($file) )
				continue;
			
			if( $flag_print )
				echo "loading: ".basename($file)."\n";
			
			require_once($file);
		}
	}
	
	echo "\nphpmira\n\n";
	
	try{
		classes_load('classes_core', 'print');
		
		/**
		 * revised workflow:
		 * 
		 * - instantiate Block
		 * 	- render plaintext to binary string (unfortunately)
		 *	- for (i = length of padded plaintext) do
		 *		- instantiate new Selection from Block based upon
		 *		1st ordinal number
		 *		- Selection->mutate()
		 *		- update Block cyphertext
		 *	- done
		 *	- render binary string to binary
		 */
		
		// TODO: complete prototype for debugging
		
		$plaintext = 'AAAABBBBCCCCDDDDEEEEFFFFHHHHIIIIJJJJKKKKLLLLMMMMNNNNOOOOPPPPQQQQ';
		
		$block = new Block($plaintext);
		
		var_dump(
			$plaintext,
			$block->binarystring_debug(),
			$block->binarystring_to_ascii()
		);
		exit(0);
	}
	catch( Exception $e )
	{
		echo "ERROR:\n\n".$e."\n\n";
	}
	
